### ISSUE TITLE
Problems with Door sensors

### ISSUE THREAD

**Issue by javed222** [moroen/ZWave-MQTT-plugin#27]
I have the same problem with the Dlink DCH-Z110 door sensors and the Fibaro FGDW-002. The ZwaveJS2Mqtt is working fine, but domoticz does not reflect state changes

**Comment by moroen** [comment]
I'm sorry, but after MQTT Auto discovery was added to the beta version of Domoticz, this plugin has been superseded and we have no current plans to continue development!

I would urge you to take a look at the new MQTT hardware in the betas, the support for zwavejs2mqtt is very good, and appear to be stable enough for daily use!
